version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: school-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Almighty1
    volumes:
      - school-db-data:/var/lib/postgresql/data
      - ./docker/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: always

volumes:
  school-db-data:
