server:
  port: 8081

spring:
  application:
    name: student-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/student_db
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
